/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

type Runtime = import("@astrojs/cloudflare").Runtime;

declare namespace App {
	interface Locals extends Runtime {}
}

// `worker-configuration.d.ts` (generated by `npx wrangler types`) declares
// `Cloudflare.Env` from wrangler.jsonc bindings — the `env` export of the
// real `cloudflare:workers` module (also declared there) is typed against
// this namespaced interface, not the bare global `Env`. Merge our
// secrets/vars into it here rather than redeclaring the whole module.
declare namespace Cloudflare {
	interface Env {
		RESEND_API_KEY: string;
		CONTACT_TO_EMAIL: string;
		CONTACT_FROM_EMAIL: string;
	}
}
